### PR TITLE
Segment rating

### PR DESCRIPTION
**Pull request by kiambogo**

### CODE REVIEW

**Comment by kiambogo** [comment]
[Make segmentCreateForm rating values to be ints, not doubles](https://trello.com/c/5d4Tgd33/54-make-segmentcreateform-rating-values-to-be-ints-not-doubles)

**Comment by kiambogo** [comment]
[Road ratings history](https://trello.com/c/CGo1GXdL/49-road-ratings-history)

**Comment by kiambogo** [comment]
[Road ratings history](https://trello.com/c/CGo1GXdL/49-road-ratings-history)

**Comment by kiambogo** [comment]
@wittjosiah what are your thoughts on segment mutability? Should a user be able to modify a segment's polyline? Or just the metadata? And what about the segment's ratings? Should the user be forced to create a new segment with their updated ratings instead of being able to modify their ratings through a pre-existing segment?

**Comment by wittjosiah** [comment]
You should only be able to edit metadata, path should be immutable.

You definitely shouldn't have to make a new segment to rate again. I think it should be something along the lines of you can edit your rating for 24 hours and make a new rating every 3 months.

**Comment by kiambogo** [comment]
So you should be able to modify the rating on a segment that you created, without deleting/creating another one. I agree. But what about segments that you didn't create show up on the map? We should be showing the average rating of the underlying ways as the rating for that segment. So perhaps we have a 'Modify my rating' button on the segment that will then display and allow you to modify the values that you rated that segment as? If you see a segment that you haven't rated before, instead of 'Modify my rating' you'll see 'Rate this segment'. Sounds good?

**Comment by wittjosiah** [comment]
Not sure how segments you create are different from segments others created, but yeah, the UI would reflect the rules we set in place for how and when you can make ratings.

**Pull request merged**
